{{- if and (not .Values.solaceCache.broker.existingSecret) .Values.solaceCache.broker.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solace-cache.fullname" . }}-credentials
  labels:
    {{- include "solace-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.solaceCache.broker.username | quote }}
  password: {{ .Values.solaceCache.broker.password | quote }}
{{- end }}
